- name: Docker container deploy
  hosts: web
  become: yes
  tasks:
    - name: Docker kur
      apt:
        name: docker.io
        state: present
        update_cache: yes
    - name: Docker başlat
      service:
        name: docker
        state: started
        enabled: yes
    - name: Eski container sil
      shell: docker rm -f devops-odevi || true
    - name: Yeni container çalıştır
      shell: docker run -d -p 80:5000 --name devops-odevi silakadagan/devops-odevi:latest
